source 'https://rubygems.org'
ruby RUBY_VERSION

gem 'jekyll', '>= 3.9.0'
gem 'jekyll-redirect-from', '>= 0.11.0'
gem 'jekyll-paginate'
gem 'crowdin-cli'
gem 'kramdown', '~> 2.3', '>= 2.3.1' # _plugins/jekyll_ext.rb messes with internals
gem 'rouge', '<2' # rouge2 will require changes in _plugins/jekyll_ext.rb
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'jekyll-assets', '~> 2.2', '>= 2.2.7'
gem 'sprockets-es6'
gem 's3_website'
gem 'octokit'
